### ISSUE TITLE
Language support EN

### ISSUE THREAD

**Issue by bprus** [nielstron/pysyncthru#19]
### Language requested: 
English

### Status values: 

 - all states: `{ status: { hrDeviceStatus: 2, status1: "", status2: "", status3: "", status4: "" }`

**Comment by nielstron** [comment]
All states? "Unknown" does still fit then, right? It is the default value and will stay it if nothing is changed.

Regarding the problem with home-assistant, "Unknown" is now not considered "offline" anymore so with the next home-assistant update/patch the failing of state fetching should be solved.

**Comment by OMdra** [comment]
my printer returns these states as READY:
```
status: { hrDeviceStatus: 3, status1: " Replace Toner", status2: "", status3: "", status4: "" }
status: { hrDeviceStatus: 3, status1: " Ready to Copy", status2: "", status3: "", status4: "" }
```

Is it possible to add these strings?

**Comment by nielstron** [comment]
This should be obsolete since status1 is not used anymore for status reporting, but only hrDeviceStatus.
