### ISSUE TITLE
Language support DE

### ISSUE THREAD

**Issue by Barma-lej** [nielstron/pysyncthru#20]
### Language requested: 
German

### Status values: 

 - **Sleeping**: `{ status: { hrDeviceStatus: 2, status1: " Sparbetrieb... ", status2: " ", status3: "", status4: "" } ...`
 - **Ready**: `status: { hrDeviceStatus: 2, status1: " Bereit: Kopie ", status2: "100% 01", status3: "", status4: "" } ...`
 - **Printing...**: `{ status: { hrDeviceStatus: 2, status1: "Wird gedruckt...", status2: " ", status3: "", status4: "" } ...`

**Comment by nielstron** [comment]
Thank you!
