### ISSUE TITLE
Language support RU

### ISSUE THREAD

**Issue by Barma-lej** [nielstron/pysyncthru#21]
### Language requested: 
Russian

### Status values: 

 - **Sleeping**: `{ status: { hrDeviceStatus: 2, status1: " Oжидaниe... ", status2: " ", status3: "", status4: "" } ...`
 - **Ready**: `status: { hrDeviceStatus: 2, status1: " Гoтoв к кoпиp. ", status2: "100% 01", status3: "", status4: "" } ...`
 - **Printing...**: `{ status: { hrDeviceStatus: 2, status1: " Идeт пeчaть... ", status2: " ", status3: "", status4: "" } ...`

**Comment by nielstron** [comment]
Thank you! I'm not that familiar with Russian so would you mind checking at #22 whether the translation from internal states to human readable strings is correct?

**Comment by Barma-lej** [comment]
"RU": {
        State.SLEEPING: 'Oжидaниe',
        State.WARMING_UP: 'Разогрев',
        State.OFFLINE: 'Не в сети',
        State.READY: 'Гoтoв',
        State.UNKNOWN: 'Неизвестно',
        State.PRINTING: 'Идeт пeчaть',
    }
