### ISSUE TITLE
Language support FR

### ISSUE THREAD

**Issue by foreign-sub** [nielstron/pysyncthru#27]
### Language requested: 
French

### Status values: 

 - **Sleeping**: `{ status: { hrDeviceStatus: 3, status1: " Veille... " ...`
 - **Ready**: `{ status: { hrDeviceStatus: 3, status1: " Pret a copier " ...`
 - **Warming up**: `{ status: { hrDeviceStatus: 3, status1: " Chauffage " ...`
 - **Printing**: `{ status: { hrDeviceStatus: 3, status1: " Impression... " ...`

**Comment by nielstron** [comment]
Done :)
