### ISSUE TITLE
Language support italian [IT]

### ISSUE THREAD

**Issue by alfry82** [nielstron/pysyncthru#29]
### Language requested: 
[Italian]

### Status values: 

 - **Sleeping**: `{ status: { hrDeviceStatus: 5, status1: " In attesa... " ...`
 - **Ready**: `{status: {hrDeviceStatus: 2, status1: "Copia pronta" ...`
 - **Warming up**: `{status: {hrDeviceStatus: 2, status1: "Riscaldamento" ...`
 - **Printing**: `{status: {hrDeviceStatus: 2, status1: "Stampa ..." ...`
 - ...
   
(whichever you have identified with your printer)

### How-To 

Access `http://your-printer-ip/sws/app/information/home/home.json` via `wget` or a webbrowser.

You can dump the result here, but the important part is `status:status1` like in the below example:
`{ status: { hrDeviceStatus: 2, status1: " Sparbetrieb... ", ...`

**Comment by nielstron** [comment]
thank you for this post! The contribution was incorporated in the latest version 0.5.1 :)
