### ISSUE TITLE
Language support EN

### ISSUE THREAD

**Issue by nielstron** [nielstron/pysyncthru#32]
my printer returns these states as READY:
```
status: { hrDeviceStatus: 3, status1: " Replace Toner", status2: "", status3: "", status4: "" }
status: { hrDeviceStatus: 3, status1: " Ready to Copy", status2: "", status3: "", status4: "" }
```

Is it possible to add these strings?

_Originally posted by @OMdra in https://github.com/nielstron/pysyncthru/issues/19#issuecomment-663820358_

**Comment by nielstron** [comment]
> Is it possible to add these strings?

Sure

> status: { hrDeviceStatus: 3, status1: " Replace Toner", status2: "", status3: "", status4: "" }

I suggest to make this the state "Low on Toner".  Or is it redundant with the percentage information about the toner? @OMdra

**Comment by OMdra** [comment]
> I suggest to make this the state "Low on Toner". Or is it redundant with the percentage information about the toner?

These two (`Ready to copy` and `Replace toner`) statuses change again and again after 3 seconds. I don't know if it's a good idea.

Toner information will be probably a better solution.
```
toner_black: {opt: 1, status: 0, remaining: 22, cnt: 707},
toner_cyan: {opt: 1, status: 0, remaining: 18, cnt: 651},
toner_magenta: {opt: 1, status: 0, remaining: 15, cnt: 652},
toner_yellow: {opt: 1, status: 2, remaining: 0, cnt: 670}
```

**Comment by nielstron** [comment]
> These two (Ready to copy and Replace toner) statuses change again and again after 3 seconds.

I see, agree that they should map to ready then

> Toner information will be probably a better solution.

But this is already displayed, right?

**Comment by nielstron** [comment]
@OMdra can you try the current dev branch?

**Comment by OMdra** [comment]
> But this is already displayed, right?
Yes, toner information works.

> can you try the current dev branch?
Not a problem, but I'll try it in the evening.

**Comment by OMdra** [comment]
I think the problem is still with capital letters.
You have in language.py `Ready To Copy` but printer returns `Ready to Copy`.
On the other side `Replace Toner` works.

**Comment by nielstron** [comment]
Thanks for the hint! Please try again with the latest commits

**Comment by OMdra** [comment]
@nielstron now it's great! Everything works for me. Thanks
