### ISSUE TITLE
Support empty status values for printers

### ISSUE THREAD

**Issue by nielstron** [nielstron/pysyncthru#35]
As documented in the [homeassistant core repo](https://github.com/home-assistant/core/issues/38258) some syncthru printer provide empty `status1` fields in http://your.printer.ip/sws/Index.html. However, they provide a different value called `hrDeviceStatus`, which is set to a non-zero value. Hence this may be used instead to interpret the device status.

**Comment by nielstron** [comment]
I just found this admin manual for samsung syncthru printers: [Samsung SCX-4828FN - SyncThru 5.0 Guide_6.68 MB, pdf, ENGLISH, MULTI LANGUAGE](https://manualsbrain.com/de/manuals/1759806/)

On page 35, a mapping from `hrDeviceStatus` to operational values is included:
| id | status |
|----|----------|
| 1 | Unknown/Normal |
| 2 | Normal |
| 3 | Warning |
| 4 | Testing |
| 5 | Down/Error |

Since these values seem to be more reliable, yet less expressive I propose to use them as primary source for the printer status, using the statusX fields for additional/more detailed status messages.

**Comment by OzGav** [comment]
As per my comment here https://github.com/home-assistant/core/issues/38258# it might be these printers don't have an LCD screen? Thus no status1/2/3/4 value...?

**Comment by nielstron** [comment]
> As per my comment here home-assistant/core#38258 it might be these printers don't have an LCD screen? Thus no status1/2/3/4 value...?

Yes agree, I think this might be one issue.

**Comment by OzGav** [comment]
Actually confirmed. Both of those other users have an M2020 printer. No screen http://h10032.www1.hp.com/ctg/Manual/c05790048

**Comment by kbalint** [comment]
@OzGav  yep, hrDeviceStatus - this could be it. mine does not have an LCD.

**Comment by nielstron** [comment]
These changes will be included in pysyncthru 0.7.0 which I will now also integrate into home assistant. Please try again with the respective branch and report any issues (https://github.com/home-assistant/core/pull/38832)

**Comment by OzGav** [comment]
Thanks so much Niels.
