### ISSUE TITLE
Tray Reporting

### ISSUE THREAD

**Issue by OzGav** [nielstron/pysyncthru#41]
**Is your feature request related to a problem? Please describe.**
The HA integration is working well since 0.115 except that tray status 1-4 is showing as unknown. This is because (a) my printer only has one tray and (b) my printer does not report anything other than tray capability (ie. paper type, paper size and tray capacity)

**Describe the solution you'd like**
Remove the reporting of tray information unless the printer reports sheets remaining.

**Describe alternatives you've considered**
You could report tray capability although I don't see how that is very useful.
You could remove the tray entities that are not physically present in the printer. This would reduce my unknowns from 4 to 1

Thanks Niels!

Looking at this
```
def input_tray_status(self, filter_supported: bool = True) -> Dict[int, Any]:
        """Return the state of all input trays."""
        tray_status = {}
        for i in range(1, 5):
            try:
                tray_stat = self.data.get("{}{}".format(SyncThru.TRAY, i), {})
                if filter_supported and tray_stat.get("opt", 0) == 0:
                    continue
                else:
                    tray_status[i] = tray_stat
            except (KeyError, AttributeError):
                tray_status[i] = {}
        return tray_status
```
I would also like to mention that the value for `opt` for my printer for trays 2-4 (which don't exist) is 2. So maybe a fix is:
`if filter_supported and tray_stat.get("opt", 0) != 1:`

**Comment by nielstron** [comment]
Thanks for mentioning this issue!

> So maybe a fix is:
if filter_supported and tray_stat.get("opt", 0) != 1:

This sounds like a useful fix.

For completeness, could you please provide the value of `tray_stat` (or the full json returned by the printer, for that matter). That way I can check which other values are candidates for being used for the filtering.

**Comment by OzGav** [comment]
Here you go. There are some more examples for other printers back in this thread https://community.home-assistant.io/t/syncthru-issue-with-0-133-0-and-samsung-printer/213573/33

```
{
	status: {
		hrDeviceStatus: 2,
		status1: " Ready to Copy",
		status2: "100%          01",
		status3: "",
		status4: ""
	},
	identity: {
		model_name: "Samsung CLX-3180 Series",
		host_name: "SEC001599876941",
		location: "",
		serial_num: "Z50UBAHB600049X ",
		ip_addr: "192.168.1.22",
		ipv6_link_addr : "FE80::215:99FF:FE87:6941/64",
		mac_addr: "00:15:99:87:69:41",
		admin_email: "",
		admin_name: "",
		admin_phone: ""
	},

	toner_black: {
		opt: 1,
		status: 0,
		remaining: 55,
		cnt: 534
	},
	toner_cyan: {
		opt: 1,
		status: 0,
		remaining: 51,
		cnt: 218
	},
	toner_magenta: {
		opt: 1,
		status: 0,
		remaining: 47,
		cnt: 446
	},
	toner_yellow: {
		opt: 1,
		status: 0,
		remaining: 47,
		cnt: 218
	},

	drum_black: {
		opt: 0,
		status: 0,
		remaining: 0
	},
	drum_cyan: {
		opt: 0,
		status: 0,
		remaining: 0
	},
	drum_magenta: {
		opt: 0,
		status: 0,
		remaining: 0
	},
	drum_yellow: {
		opt: 0,
		status: 0,
		remaining: 0
	},
	
	tray1: {
		opt: 1,
		paper_size1: 4,
		paper_size2: 0,
		paper_type: 64,
		capa: 130,
		status: 2
	},
	tray2: {
		opt: 2,
		paper_size1: 4,
		paper_size2: 0,
		paper_type: 0,
		capa: 0,
		status: 0
	},
	tray3: {
		opt: 2,
		paper_size1: 0,
		paper_size2: 0,
		paper_type: 0,
		capa: 0,
		status: 0
	},
	tray4: {
		opt: 2,
		paper_size1: 0,
		paper_size2: 0,
		paper_type: 0,
		capa: 0,
		status: 0
	},
	mp: {
		opt: 0,
		paper_size1: 4,
		paper_size2: 0,
		paper_type1: 64,
		paper_type2: 63,
		capa: 1,
		status: 1
	},
	outbin: [
		["BIN1", 0, 1] 

	],
	capability: {
		hdd: {opt: 2, capa: 0},
		ram: {opt: 262144, capa: 262144},
		scanner: {opt: 0 , capa: 0}
	},

	options: {
		fax: 1,extendedMem: 2,wlan: 0
	},
	GXI_ACTIVE_ALERT_TOTAL: 1,
	GXI_ADMIN_WUI_HAS_DEFAULT_PASS: 1
}
```

**Comment by nielstron** [comment]
Thanks. I am wondering what "mp" and "manual" are about, they look as if they were additional input trays. I will also include them, currently working on this in branch `fix_tray_support`

**Comment by nielstron** [comment]
Should be resolved via #42

**Comment by OzGav** [comment]
I was going to say they were the same thing - manual feeder. However I see that the SCX-4726FD is reporting both `mp` and `manual`. I checked the user guide for the SCX-4726FD and it does have a `manual feeder` so I am going to say that manual means that. Haven't been able to work out `mp` yet as all the printers that people have posted about have `opt: 0` for that...

https://www.yumpu.com/it/document/read/54644633/samsung-scx-4726fd-user-manual-1208-mb-pdf-english

edit: Should have looked a bit harder. `mp` = multi-purpose tray

**Comment by nielstron** [comment]
> Should have looked a bit harder. mp = multi-purpose tray

Thanks for looking that up!

**Comment by nielstron** [comment]
Closing this since there seems nothing missing anymore
