### ISSUE TITLE
SyntaxError with python3.8

### ISSUE THREAD

**Issue by Warter21** [nielstron/pysyncthru#49]
Hi!

I got a strange error if I try to import SyncThru. It is working fine with python3.7 but drops error with python3.8.

`Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiohttp
>>> import asyncio
>>> from pysyncthru import SyncThru
>>> 

Python 3.8.6 (default, Oct 11 2020, 14:34:16) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiohttp
>>> import asyncio
>>> from pysyncthru import SyncThru
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pysyncthru/__init__.py", line 3, in <module>
    import demjson
  File "/usr/local/lib/python3.8/dist-packages/demjson.py", line 645
    class json_int( (1L).__class__ ):    # Have to specify base this way to satisfy 2to3
                      ^
SyntaxError: invalid syntax
>>> 
`

Please advise.

Thanks,
Warter

**Comment by nielstron** [comment]
That's odd. However, the error is not thrown inside pysyncthru but inside the 'demjson' package (which is a requirement). Maybe you can try to upgrade the demjson installation in the python package you are using or open an Issue over at [demjson](https://github.com/dmeranda/demjson/)

UPDATE: I also cannot reproduce this error locally (nor does it occur in the travis build). So I am not exactly sure what is the issue in your installation.

**Comment by Warter21** [comment]
It is a Debian Buster on arm with a backport package. Maybe it relates to the python package. I am not sure. But thanks for your comment.

UPDATE: it seems the demjson.py is different for 3.7 than 3.8. If I use the 3.7 version for python3.8. it is working fine.

**Comment by Warter21** [comment]
the problem is in demjson.
