### ISSUE TITLE
Add support for more printers (e.g. SCX-4623) using alternative data source

### ISSUE THREAD

**Issue by pegelf** [nielstron/pysyncthru#50]
In the [Home Assistant Issues](https://github.com/home-assistant/core/issues/43563) I saw that there are some printer models which doesn't host a home.json. Do you still want to support those printers?

I captured the network traffic but the SyncThru web page of my SCX-4623 printer doesn't use an internal Rest-API, but instead HTML-files are generated which sometimes contain Javascript-code.

For example when I access http://192.168.137.35/Information/supplies_status.htm I can see a web page which is normally embedded in an iFrame. On line 11, there is the javascript declaration _var BlackTonerPer	= 66;_ which is the current toner level.

If you want to see the current display content, the printer name and the tray status, you have to open http://192.168.137.35/home.htm

In this file, also some javascript variables are defined so maybe to get those values, it could be an option to just search for a line which starts with the declaration. I don't know the python-command for that. In my case the variables are:

```
var faxTrayVisible = "Supported";
var copyTrayVisible = "Supported";
var tray2Installed = "Not Installed";
var tray3Installed = "Invisible";
var tray4Installed = "Invisible";
var hcfInstalled = "0";
var drumInstalled = "Not Installed";
var faxInstalled = "Installed";

var mfTrayStatus = "Ready";
var tray1Status = "Ready";
var tray2Status = "Ready";
```

The printer name isn't saved in a Javascript variable so for that you would need to parse the HTML code.

I just attached the HTML files, so you can have a look on it if you want to.

[SCX-4623.zip](https://github.com/nielstron/pysyncthru/files/6679829/SCX-4623.zip)

**Comment by nielstron** [comment]
Thank you very much for the suggestion! I think the approach of parsing for the instantiation of certain lines is a good idea. I need to additionally check if the files you provided are present (even) if the home.json is present. In any case, the page you suggest to use may be a good source of supplemental information.

As "python" command, I suggest to use a regex like `var\s+([a-zA-Z0-9]+)\s*=\s*([a-zA-Z0-9]*);` or a javascript parsing library.
