### ISSUE TITLE
Tags on GitHub

### ISSUE THREAD

**Issue by dotlambda** [nielstron/pysyncthru#51]
**Is your feature request related to a problem? Please describe.**
Installing stable versions from GitHub is impossible

**Describe the solution you'd like**
It would be nice if releases appeared on https://github.com/nielstron/pysyncthru/releases.

**Comment by nielstron** [comment]
There are currently two ways to install the package.
1. Installing via pip. The latest version in the master branch and the version hosted on pipy.com are identical.
2. Installing via git
       - Clone the repository (https://github.com/nielstron/pysyncthru)
       - Run `pip install -e .` in the repository root

I don't see why it should be necessary to be able to download a "release" version of the package from github, could you further explain?

**Comment by dotlambda** [comment]
> I don't see why it should be necessary to be able to download a "release" version of the package from github, could you further explain?

The sdists on PyPI don't contain the tests.

**Comment by nielstron** [comment]
Version 0.7.3 was now tagged manually, all future versions will be released and tagged automatically.
