### ISSUE TITLE
demjson fails to install with setuptools v58.0.0

### ISSUE THREAD

**Issue by KapJI** [nielstron/pysyncthru#55]
**Describe the bug**
It's quite an old package and relies on `2to3` for Python 3 support. It hasn't received updates since 2015.

Setuptools removed support of 2to3 in 58.0.0: https://setuptools.readthedocs.io/en/latest/history.html

Can you replace it with something more modern? From what I see in the code standard `json` module should be sufficient.

Example of build failure: https://github.com/home-assistant/core/pull/55911/checks?check_run_id=3536805590

**Comment by nielstron** [comment]
Hi KapJI,

unfortunately `json` does not work (look at the test cases, I tried and failed).

Indeed I would be very happy to replace demjson but have not found a package that works with the input data nor the time to build one myself.

**Comment by nielstron** [comment]
Okay well, here we go: https://github.com/nielstron/demjson3

**Comment by nielstron** [comment]
Should be fixed in https://github.com/nielstron/pysyncthru/releases/tag/release-0.7.10 since now demjson3 is a requirement instead of demjson

**Comment by KapJI** [comment]
Thanks for the quick fix!

Please also revert https://github.com/home-assistant/core/pull/55911/commits/efe00b3f0f796bbee058a5f7f0ab44955d1d0b5e in https://github.com/home-assistant/core/pull/55894
