### ISSUE TITLE
[FR] please include an AirPrinter-Proxy / MobilePrint-Proxy for IPP to wire connected Samsung printers

### ISSUE THREAD

**Issue by ifrh** [nielstron/pysyncthru#58]
Is it possible to introduce for wired connected Samsung printers "speaking IPP" 
like SAMSUNG SCX 4828FN software proxys that simulates 
- AirPrinter-compatibility for iOS Systems of iPhone and iPad
- MobilePrint-compatibility for Android Systems of Phones and Tablets?

Neighter iOS nor Android mobile Devices find the wired printer in WLAN as available or usable.
But Windows and Linux Systems can find the printer in WLAN and prints via IPP.

There exists a AirPrinter-Proxy project based on nodejs: https://github.com/SuperMarcus/airprint-proxy.
That software produced correct information to simulate that the Samsung printer is a AirPrinter,
the iOS mobile devices find that printer information, but sadly the SAMSUNG printer did not start the printing job.

And here exists an Python-IPP client project : https://github.com/ctalkington/python-ipp

**Comment by nielstron** [comment]
This appears clearly out of scope for a component designed to connect to "syncthru" based devices. Thank you for collecting the the references however.
